/**
 * 元素的类型
 * 因为想用数字枚举类型但是需要跟后端保持一致，后端采用kotlin不支持数字枚举类型这样使用。
 */
export enum ElementType {
    SINGLE_IMAGE = "SINGLE_IMAGE",
    COLOR_BLOCK = "COLOR_BLOCK",
    GENERAL_TITLE = "GENERAL_TITLE",
    DIGITAL_CARD_FLIPPER = "DIGITAL_CARD_FLIPPER",
    STACKED_COLUMN_CHART = "STACKED_COLUMN_CHART",
    BAR_WITH_BACKGROUND = "BAR_WITH_BACKGROUND",
    MULTIPLE_X_AXES = "MULTIPLE_X_AXES",
    BUS_LINE = "BUS_LINE",
    DOUGHNUT_CHART_WITH_ROUNDED_CORNER = "DOUGHNUT_CHART_WITH_ROUNDED_CORNER",
    BUBBLE_CHART = "BUBBLE_CHART",
    FOLDER = "FOLDER",
}
